
// Objective-C API for talking to the following Go packages
//
//	shenganlee.com/gowebserver
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gowebserver_FRAMEWORK_H__
#define __Gowebserver_FRAMEWORK_H__

#include "Gowebserver.objc.h"
#include "Universe.objc.h"

#endif
