// Objective-C API for talking to shenganlee.com/gowebserver Go package.
//   gobind -lang=objc shenganlee.com/gowebserver
//
// File is generated by gobind. Do not edit.

#ifndef __Gowebserver_H__
#define __Gowebserver_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GowebserverProxy;

@interface GowebserverProxy : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull path;
@property (nonatomic) NSString* _Nonnull target;
// skipped field Proxy.Include with unsupported type: []string

// skipped field Proxy.Exclude with unsupported type: []string

@end

/**
 * 获取未被使用的端口
 */
FOUNDATION_EXPORT long GowebserverGetPort(long startPort);

FOUNDATION_EXPORT void GowebserverRestart(NSString* _Nullable addr);

FOUNDATION_EXPORT NSString* _Nonnull GowebserverStart(NSString* _Nullable fileDir, NSString* _Nullable proxyStr);

FOUNDATION_EXPORT void GowebserverStop(NSString* _Nullable addr);

#endif
